### PR TITLE
Search PLEX_MEDIA_SERVER_USER

### LINKED ISSUE #196: Can't get plex token if running as different user
This is similar to #181. I run plex as a different user than the default plex (not root), and the app directory is in that user's $HOME. This is on Ubuntu 14.04, so I do this by changing PLEX_MEDIA_SERVER_USER in  /etc/default/plexmediaserver. I did not need to change PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR from the default which is commented out.

When plexupdate runs as root, it looks for Plex in the 3 paths in $VALIDPATHS. Since it's running as root, it looks in root's $HOME but not the $HOME of the user PLEX_MEDIA_SERVER_USER. When not finding these, the script prompts for token or reverts back to public, which results in downgrading plex if running a PlexPass build. 

This case could be addressed by adding another path to VALIDPATHS:  "/home/${PLEX_MEDIA_SERVER_USER}/Library/Application Support/"

### PR DESCRIPTION
**Pull request by dbarboza**
Fixes #196 by searching the $HOME of PLEX_MEDIA_SERVER_USER

### CODE REVIEW

**Comment by demonbane** [comment]
We should just query the system for the user's home directory instead of hard-coding /home:

```bash
getent passwd "$PLEX_MEDIA_SERVER_USER" | cut -d: -f6
```

If it's an invalid user, it'll be the same effect as `$HOME` being empty; i.e. `/Library/Application Support`

**Comment by mrworf** [comment]
True, but we still need to make sure we don't use a blank resolved address. So something like:

```
ALTHOME="$(getent passwd "$PLEX_MEDIA_SERVER_USER" | cut -d: -f6)"
if [ -z "$ALTHOME" -o ! -d "$ALTHOME" ]; then 
  ALTHOME="$HOME"
fi
```

**Comment by demonbane** [comment]
@dbarboza I just talked to @mrworf about this, and there's a few other things we want to do with this function as well to make it a bit more resilient. Would you be interested in helping out with that as well, or do you just want to get this bit fixed ASAP so you can go back to using it?

**Comment by demonbane** [comment]
@dbarboza did you want to continue working on this or would you like me to just get it cleaned up and merged?

**Pull request closed without merging**
