### PR TITLE
Argument changes

### PR DESCRIPTION
**Pull request by mscreations**
Okay, feel free to pull this in if you choose. Basically, what this patch does is makes a few changes to the command line parsing. It makes it so that rather than the config file being the last item in the list of arguments, it is now following a long option parameter (--config). There are some other long options that enable the user to define everything from the command line. There is also an option that will allow you to save your settings as they stand to the configuration file. 

I also fixed some issues with tabs that had been converted to spaces, as well as fixed some spelling mistakes in README.md.

Let me know if this is okay, or if you want me to make any changes before it get's pulled in.

### CODE REVIEW

**Comment by mrworf** [comment]
I like the idea that a user can completely sidestep the need for .plexupdate file, but I think adding the option to save configuration is a bit overkill and makes the code more convoluted than necessary.

As a side-note, erasing ' from passwords is dangerous, people have been known to use them.

**Comment by mscreations** [comment]
Okay, I pushed another commit that fixes the removal of single quotes from passwords (and all other fields). 

As for the option to save the configuration, my logic behind that was that I could run the script once from the command line and all subsequent times running it would be a simpler call to the script. If you want I can strip it back out, but it is helpful in getting the file created correctly. 

The only other thing I had forgotten to mention and shall mention now, is this will break user's who are currently specifying their config file on the command line. I wasn't sure how to handle that particular case. I could make it so it would take a look at the last argument and if it was a valid config file use it, but I'm not sure how much extra code that might entail. Let me know what you think.

**Comment by mscreations** [comment]
I made a quick fix to alert the user if the config is being used the old way (as the last option in the command line) so it won't break any user's setup. I also removed some unnecessary code from my last commit. Let me know what you want me to do with the save config option.

**Comment by mscreations** [comment]
Any thoughts on this? Anything that needs changed or omitted?

**Pull request merged**
